version: "3.7"

services:
  reporting-service:
    image: reporting-service:v0
    deploy:
      mode: replicated
      replicas: 2

    environment:
      - SUBSCRIPTION_ID=reservation-created-sub
    volumes:
      - ./reporting-service/credentials.json:/credentials.json

  other-service:
    image: reporting-service:v0
    deploy:
      mode: replicated
      replicas: 1

    environment:
      - SUBSCRIPTION_ID=reservation-created-sub-2
    volumes:
      - ./reporting-service/credentials.json:/credentials.json